language: go
go:
  - tip
env:
  global:
      - NDK_VERSION=r20
      - ANDROID_NDK_HOME=$HOME/.android/android-ndk-${NDK_VERSION}
      - ANDROID_ARM_CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi29-clang
      - ANDROID_ARM_STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
      - ANDROID_X86_CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android29-clang
      - ANDROID_X86_STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-strip
      - ANDROID_AARCH64_CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang
      - ANDROID_AARCH64_STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip
      - ANDROID_X64_CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android29-clang
      - ANDROID_X64_STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-strip
      - PATH=${ANDROID_NDK_HOME}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}

install:
  - >
    if [ ! -d "$ANDROID_NDK_HOME" ]; then
        mkdir -p $ANDROID_NDK_HOME;
        pushd $HOME/.android;
        export ARCH=`uname -m`;
        wget -q http://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
        unzip -q android-ndk-${NDK_VERSION}-linux-${ARCH}.zip;
        popd;
    fi
script:
  - pwd && ls -l
  - env CGO_ENABLED=1 CC=$ANDROID_ARM_CC GOOS=android GOARCH=arm GOARM=7 go build -o assets/avege -ldflags="-s -w" && cd assets && tar czvf avege-android-armv7.tar.gz avege conf resources templates config-sample.json
  - env CGO_ENABLED=1 CC=$ANDROID_X86_CC GOOS=android GOARCH=386 go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-android-386.tar.gz avege conf resources templates config-sample.json
  - env CGO_ENABLED=1 CC=$ANDROID_AARCH64_CC GOOS=android GOARCH=arm64 go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-android-arm64.tar.gz avege conf resources templates config-sample.json
  - env CGO_ENABLED=1 CC=$ANDROID_X64_CC GOOS=android GOARCH=amd64 go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-android-amd64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-amd64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=386 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-386.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=arm GOARM=5 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-armv5.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=arm GOARM=6 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-armv6.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=arm GOARM=7 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-armv7.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=arm64 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-arm64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=ppc64 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-ppc64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=ppc64le GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-ppc64le.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=mips64 GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-mips64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=mips64le GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-mips64le.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=mips GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-mips.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=mipsle GOOS=linux go build -o assets/avege -ldflags="-s -w"  && cd assets && tar czvf avege-linux-mipsle.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=darwin go build -o assets/avege  && cd assets && tar czvf avege-darwin-amd64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=windows go build -o assets/avege.exe  && cd assets && tar czvf avege-windows-amd64.tar.gz avege.exe conf resources templates config-sample.json
  - env GOARCH=386 GOOS=windows go build -o assets/avege.exe  && cd assets && tar czvf avege-windows-386.tar.gz avege.exe conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=freebsd go build -o assets/avege  && cd assets && tar czvf avege-freebsd-amd64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=386 GOOS=freebsd go build -o assets/avege  && cd assets && tar czvf avege-freebsd-386.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=arm GOOS=freebsd go build -o assets/avege  && cd assets && tar czvf avege-freebsd-arm.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=openbsd go build -o assets/avege  && cd assets && tar czvf avege-openbsd-amd64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=386 GOOS=openbsd go build -o assets/avege  && cd assets && tar czvf avege-openbsd-386.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=netbsd go build -o assets/avege  && cd assets && tar czvf avege-netbsd-amd64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=386 GOOS=netbsd go build -o assets/avege  && cd assets && tar czvf avege-netbsd-386.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=arm GOOS=netbsd go build -o assets/avege  && cd assets && tar czvf avege-netbsd-arm.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=dragonfly go build -o assets/avege  && cd assets && tar czvf avege-dragonflybsd-amd64.tar.gz avege conf resources templates config-sample.json
  - env GOARCH=amd64 GOOS=solaris go build -o assets/avege  && cd assets && tar czvf avege-solaris-amd64.tar.gz avege conf resources templates config-sample.json
deploy:
  provider: releases
  api_key:
    secure: qROlG3DcJ0KV4iucaggSGshDNZspXnL336bnsserCG0337wAmHT08sfdOZMHORZ4hmzNnMvoj1ImU7eW7v1JprphD3npf9jj0Ns/2zM2lydrXGAGcCF0Ec0r8b5ZLS9CKZ+0wftkfHXDThWxJvC7g01L52BsxIPfFqkCZIexMwGG3xAwxYnVP6CFJ7U9+dOzhGsjTG6UxvWb4eMZsM0oqa18aT1tMmuiYw/5Y4RpngKPl/BafiyriTLP88PoyY/SpJS3ttggymH5IXIbBGHzlNK6f5/Niz76TDhTtimH65xT/QgUrFJJMlMtbntraxYvwCBhgADM95AA7ncv0GKXiAJswnjPknVRzAtxRdUopY0Spblln0HjZuYjimbbmtv5OZaARgHK1/gQS8p2EGnsXzAFuY9asWGHlkayIxFYx1rQXwIMERrX4v6BwBqEK6ni6DwMxtlxF9rQvpZ2/Q8w/BzexEN8p1zQD784SS/UdWr2P81OsEH9wx+X8Z7Eyw4FM6XP6EMC+412xASLDhQwJK90ut7fME5BAOipgCx6rCaXlxm2e/XVNB6ZlB41mj42HmlvJzvi0i648yRtKHmqEv6Ff82LGET4PapT7OFES9MSZUupSr7NGocs4v8XGhrhL607ugJcC2qP5ZHy4eqGREImyYsdkv+T7lZazEuRe8s=
  file: 
    - assets/avege-android-armv7.tar.gz
    - assets/avege-android-386.tar.gz
    - assets/avege-android-amd64.tar.gz
    - assets/avege-android-arm64.tar.gz
    - assets/avege-darwin-amd64.tar.gz
    - assets/avege-dragonflybsd-amd64.tar.gz
    - assets/avege-freebsd-amd64.tar.gz
    - assets/avege-freebsd-arm.tar.gz
    - assets/avege-freebsd-386.tar.gz
    - assets/avege-linux-amd64.tar.gz
    - assets/avege-linux-arm64.tar.gz
    - assets/avege-linux-armv5.tar.gz
    - assets/avege-linux-armv6.tar.gz
    - assets/avege-linux-armv7.tar.gz
    - assets/avege-linux-mips64.tar.gz
    - assets/avege-linux-mips64le.tar.gz
    - assets/avege-linux-mips.tar.gz
    - assets/avege-linux-mipsle.tar.gz
    - assets/avege-linux-ppc64.tar.gz
    - assets/avege-linux-ppc64le.tar.gz
    - assets/avege-linux-386.tar.gz
    - assets/avege-netbsd-amd64.tar.gz
    - assets/avege-netbsd-arm.tar.gz
    - assets/avege-netbsd-386.tar.gz
    - assets/avege-openbsd-amd64.tar.gz
    - assets/avege-openbsd-386.tar.gz
    - assets/avege-solaris-amd64.tar.gz
    - assets/avege-windows-amd64.tar.gz
    - assets/avege-windows-386.tar.gz
  on:
    repo: missdeer/avege
    tags: true
  skip_cleanup: true
